// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";

export interface IPhotoEssayFields {
  /** Title */
  title?: string | undefined;

  /** Date */
  date?: string | undefined;

  /** Location */
  location?: { lat: number; lon: number } | undefined;

  /** Slug */
  slug: string;

  /** Photos */
  photos?: Asset[] | undefined;
}

export interface IPhotoEssay extends Entry<IPhotoEssayFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "photoEssay";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPhotoWithCaptionFields {
  /** Photo */
  photo?: Asset | undefined;

  /** Caption */
  caption?: string | undefined;
}

export interface IPhotoWithCaption extends Entry<IPhotoWithCaptionFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "photoWithCaption";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE = "photoEssay" | "photoWithCaption";

export type IEntry = IPhotoEssay | IPhotoWithCaption;

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
